<?php
$this->headTitle()->append("Image Gallery Albums");

$getters = array();

foreach ($this->albumlistElements as $element) {
    $parts = explode('_', $element);
    array_walk($parts, function (&$val) {
        $val = ucfirst($val);
    });
    $getters[$element] = 'get' . implode('', $parts);
}
?>

<h1><?php echo $this->translate('Image Gallery Albums') ?></h1>

<div class="navbar filter-bar">
    <div class="navbar-inner">
        <div class="pull-right">
            <a href="<?php echo $this->url('zfcadmin/wdg-imagegallery-admin/album/add') ?>" class="btn btn-primary">
                <?php echo $this->translate('Add New Album') ?>
            </a>
        </div>
    </div>
</div>

<table class="table">
    <thead>
        <tr>    
            <th style="width:40px;">&nbsp</th>
            <?php foreach ($this->albumlistElements as $name => $element): ?>
                <th><?php echo $this->escapeHtml($name ? : $element); ?></th>
            <?php endforeach; ?>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    <?php 
    foreach($this->albums as $album)
    {
        ?>
        <tr>
            <td>
                <a title="Show Album" href="<?php echo $this->url("zfcadmin/wdg-imagegallery-admin/album/show", array("id" => $album->getId()));?>">
                    <?php echo $album->getId();?>
                </a>
            </td>
            
            <?php 
            foreach ($this->albumlistElements as $element): ?>
                <td class="cell cell-<?php echo $this->escapeHtml($element) ?>">
                    <?php $parts = explode('_', $element); ?>
                    <?php echo call_user_func(array($album, $getters[$element])); ?>
                </td>
            <?php endforeach; ?>
                
            <td class="cell cell-ctrls">
                <a href="<?php echo $this->url('zfcadmin/wdg-imagegallery-admin/album/edit', array('id' => $album->getId())); ?>">
                    <?php echo $this->translate('Edit') ?>
                </a>
                |
                <a href="<?php echo $this->url('zfcadmin/wdg-imagegallery-admin/album/delete', array('id' => $album->getId())); ?>"
                   onclick="return confirm('<?php echo $this->translate('Really delete album?') ?>')">
                    <?php echo $this->translate('Delete') ?>
                </a>
            </td>
        </tr>
        <?php
    }
    ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="<?php echo count($this->albumlistElements) + 2; ?>">
                <?php echo $this->paginationControl($this->albums, 'Sliding', 'partial/paginator-item-control.phtml'); ?>
            </td>
        </tr>
    </tfoot>
</table>